name: Generate changelog

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Checkout wiki repository
        uses: actions/checkout@v3
        with:
          repository: c2corg/c2c_ui.wiki
          ref: master
          path: wiki
      - name: Configure git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Generate changelog
        id: changelog
        uses: c2corg/generate-changelog-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Save changelog to file
        run: |
          echo "$CHANGELOG" > wiki/Changelog.md
        env:
          CHANGELOG: ${{ steps.changelog.outputs.changelog }}
      - name: Commit files
        working-directory: wiki
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add Changelog.md
          git commit -m "Update changelog"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: wiki
          repository: c2corg/c2c_ui.wiki
          github_token: ${{ secrets.GITHUB_TOKEN }}
