name: Retrieve i18n from Transifex

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  retrieve-18n:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configure git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Retrieve i18n from Transifex and create PR if applies
        uses: c2corg/transifex-pull-request-action@b4b1289f96385da92ec34a26da51892d269b7e0e
        with:
          transifex_token: ${{ secrets.TRANSIFEX_TOKEN }}
          transifex_organisation: camptocamp-association
          transifex_project: c2corg_ui
          transifex_resource: main
          output: src/translations
          locales: ca, de, en, es, eu, fr, hu, it, ru, sl, zh_CN
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: transifex/i18n
          labels: i18n
